#!/usr/bin/env python
import sys, os.path, inspect


def main():
  pyfile = sys.argv[1]; runcode = ' '.join(sys.argv[2:]);
  filedir = os.path.split(pyfile)[0]
  sys.path.insert(0, filedir)
  module = __import__(pyfile[:-3], globals(), locals(), ['*'])
  for k in dir(module):
    locals()[k] = getattr(module, k)

  from StringIO import StringIO
  saved_stdout = sys.stdout; catch_out = StringIO(); sys.stdout = catch_out;
  try:
    glob = globals(); loc = locals();
    exec(runcode, glob, loc)
  finally:
    sys.stdout = saved_stdout
  if len(catch_out.getvalue()):
    print catch_out.getvalue().strip()

main()